#!/bin/bash

sudo yum install -y httpd



sudo chown -R ec2-user:ec2-user /var/log/

sudo  systemctl start httpd 

echo "<!DOCTYPE html>
<html>
	<head>
		    <title>Hello World!</title>
	</head>
	<body>
		    <h1>Hello World!</h1>
	</body>
</html>
" >>  /var/www/html/index.html

sudo chown -R ec2-user:ec2-user /var/www/